scrape_configs:
  - job_name: rabbit
    scrape_interval: 15s
    scheme: http
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:15692']

